module.exports = {
  purge: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./containers/**/*.{ts,tsx}",
    "./assets/**/*.{ts,tsx}",
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    fontSize: {
      xs: "10px",
      sm: "12px",
      base: "14px",
      xl: "16px",
      "2xl": "20px",
      "3xl": "22px",
      "4xl": "26px",
    },
    extend: {
      animation: {
        "spin-slow": "spin 3s linear infinite",
        "pumpkin-right": "changePlaceRight 6s infinite alternate;",
        "pumpkin-left": "changePlaceLeft 6s infinite alternate;",
      },
      scale: {
        1000: "1000%",
      },
      boxShadow: {
        key: "black 2px 4px",
        1: "var(--box-shadow-1)",
        2: "var(--box-shadow-2)",
        3: "var(--box-shadow-3)",
        4: "var(--box-shadow-4)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
      },
      width: {
        app: "90%",
        card: "314px",
        "98%": "98%",
        "94%": "94%",
        "1/7": "14.2857143%",
        "2/7": "28.5714286%",
        "3/7": "42.8571429%",
        "4/7": "57.1428571%",
        "5/7": "71.4285714%",
        "6/7": "85.7142857%",
      },
      maxWidth: {
        app: "var(--app-width)",
      },
      height: {
        card: "314px",
      },
      colors: {
        primaryLight: "var(--color-primaryLight)",
        primary: "var(--color-primary)",
        primaryDark: "var(--color-primaryDark)",
        header: "var(--color-header)",
        topbar: "var(--color-topbar)",
        onTopbar: "var(--color-onTopbar)",
        menuButton: "var(--color-menuButton)",
        onMenuButton: "var(--color-onMenuButton)",
        infobar: "var(--color-infobar)",
        onInfobar: "var(--color-onInfobar)",
        footer: "var(--color-footer)",
        onFooter: "var(--color-onFooter)",

        onPrimary: "var(--color-onPrimary)",
        secondary: "var(--color-secondary)",
        onSecondary: "var(--color-onSecondary)",

        onSurfaceLinkHigh: "var(--color-onSurfaceLinkHigh)",
        onSurfaceLinkMedium: "var(--color-onSurfaceLinkMedium)",
        onSurfaceLinkLow: "var(--color-onSurfaceLinkLow)",

        onPrimaryLinkHigh: "var(--color-onPrimaryLinkHigh)",
        onPrimaryLinkMedium: "(--color-onPrimaryLinkMedium)",
        onPrimaryLinkLow: "var(--color-onPrimaryLinkLow)",

        onPrimaryHigh: "var(--color-onPrimaryHigh)",
        onPrimaryMedium: "var(--color-onPrimaryMedium)",
        onPrimaryLow: "var(--color-onPrimaryLow)",

        onSurfaceHigh: "var(--color-onSurfaceHigh)",
        onSurfaceMedium: "var(--color-onSurfaceMedium)",
        onSurfaceLow: "var( --color-onSurfaceLow)",

        onSurfacePrimaryHigh: "var(--color-onSurfacePrimaryHigh)",
        onSurfacePrimaryMedium: "var(--color-onSurfacePrimaryMedium)",
        onSurfacePrimaryLow: "var(--color-onSurfacePrimaryLow)",

        "surface-0": "var(--color-surface)",
        surface: "var(--color-surface)",
        "surface-1": "var(--color-surface-1)",
        "surface-2": "var(--color-surface-2)",
        "surface-3": "var(--color-surface-3)",
        "surface-4": "var(--color-surface-4)",
        "surface-5": "var(--color-surface-5)",
        "surface-6": "var(--color-surface-6)",
        "surface-7": "var(--color-surface-7)",
        "surface-8": "var(--color-surface-8)",

        background: "var(--color-background)",
        onBackgroundLow: "var(--color-onBackgroundLow)",
        onBackgroundMedium: "var(--color-onBackgroundMedium)",
        onBackgroundHigh: "var(--color-onBackgroundHigh)",

        red: "var(--color-red)",
        yellow: "var(--color-yellow)",
        green: "var(--color-green)",
        accentPrimary: "var(--color-accentPrimary)",
        accentSecondary: "var(--color-accentSecondary)",
        onAccentSecondary: "var(--color-onAccentSecondary)",
        accentTertiary: "var(--color-accentTertiary)",
        error: "var(--color-error)",
        success: "var(--color-success)",
        successOpacity: "var(--color-success-opacity)",
        info: "var(--color-info)",
        onError: "var(--color-onError)",
        onErrorVariant: "var(--color-onErrorVariant)",
        onSuccess: "var(--color-onSuccess)",
        onSuccessVariant: "var(--color-onSuccessVariant)",
        warning: "var(--color-warning)",
        onWarning: "var(--color-onWarning)",
        onInfo: "var(--color-onInfo)",
        onInfoVariant: "var(--color-onInfoVariant)",
      },
    },
  },
  variants: {
    extend: {
      padding: ["hover"],
      zIndex: ["active", "hover"],
      display: ["group-hover"],
      textColor: ["group-hover"],
      animation: ["responsive", "motion-safe", "motion-reduce"],
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
